In [1]:
import numpy

ModuleNotFoundError: No module named 'numpy'

In [2]:
 import numpy

In [4]:
import numpy as jey

In [5]:
a=jey.array([1,2,3])

In [6]:
print(a)

[1 2 3]


In [7]:
c=jey.array([(1,2,3),(4,5,6)])

In [8]:
print(c)

[[1 2 3]
 [4 5 6]]


In [11]:
trans=jey.transpose(c)

In [12]:
print(trans)

[[1 4]
 [2 5]
 [3 6]]


In [13]:
trans.ravel()

array([1, 4, 2, 5, 3, 6])

In [19]:
c.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [17]:
ze=jey.zeros((1,3))

In [18]:
print(ze)

[[0. 0. 0.]]


In [20]:
one=jey.ones((3,3))

In [21]:
print(one)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [22]:
jey.random.random((5,5))

array([[0.48417208, 0.86914794, 0.15859825, 0.47419113, 0.23781876],
       [0.88717129, 0.42359851, 0.05761759, 0.82818813, 0.0693273 ],
       [0.18336472, 0.33158236, 0.99894934, 0.10195927, 0.98266218],
       [0.66181225, 0.15379818, 0.10440494, 0.66924462, 0.07823065],
       [0.90020708, 0.94045539, 0.86444027, 0.15918716, 0.60052399]])